---
- name: "Test AsterNOS CLI"
  hosts: asterfusionswitch
  gather_facts: false

  tasks:
    - name: Add interface
      asterfusion.asternos.asternos_command:
        commands:
          - configure
          - interface loopback 10
          - ip address 10.5.10.1/24

    - name: Show running-config
      asterfusion.asternos.asternos_command:
        commands:
          - show running-config
      register: cmd_op

    - name: Print vars
      ansible.builtin.debug:
        msg: "{{ cmd_op.stdout_lines }}"

    - name: Write config
      asterfusion.asternos.asternos_command:
        commands:
          - command: 'write'
            prompt: '\[y/N\]: $'
            answer: 'y'
