---
- name: "Test AsterNOS CLI"
  hosts: asterfusionswitch
  gather_facts: true

  tasks:



  - name: Add interface
    asterfusion.asternos.asternos_command:
       commands:
         - configure
         - interface loopback 10
         - ip address 10.5.10.1/24

  - name: Show running-config
    asterfusion.asternos.asternos_command:
       commands:
         - show running-config

    register: cmd_op
  - name: Print vars
    debug:
      msg: "{{cmd_op.stdout_lines}}"
 

#  - name: "Test asternos_command module: write command with prompt handling"
#    asterfusion.asternos.asternos_command:
#       commands:
#         - command: 'write'
#           prompt: '\[y/N\]: $'
#           answer: 'y'